-- H2 2.1.214; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'd1113e33bd598a29' HASH 'ab9294b6477245bb0e0c558e6d8b8d039414fe8d9bfe39ecb77a96c1542dd151' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."PERSON"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "NAME" CHARACTER VARYING(100)
);            
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;   
INSERT INTO "PUBLIC"."PERSON" VALUES
(1, 'Kaire Kask');        
CREATE CACHED TABLE "PUBLIC"."PERSON_IN_SECTOR"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 9) NOT NULL,
    "AGREE_TERMS" BOOLEAN,
    "PERSON_ID" BIGINT,
    "SECTORTYPE_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."PERSON_IN_SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");              
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PERSON_IN_SECTOR;         
INSERT INTO "PUBLIC"."PERSON_IN_SECTOR" VALUES
(7, TRUE, 1, 67),
(8, TRUE, 1, 69);             
CREATE CACHED TABLE "PUBLIC"."SECTOR_TYPE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 80) NOT NULL,
    "TYPE_NAME" CHARACTER VARYING(255),
    "CHILD_ID" BIGINT,
    "GRANNY_ID" BIGINT,
    "PARENT_ID" BIGINT
);          
ALTER TABLE "PUBLIC"."SECTOR_TYPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E6" PRIMARY KEY("ID");  
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SECTOR_TYPE;             
INSERT INTO "PUBLIC"."SECTOR_TYPE" VALUES
(1, 'Manufacturing', NULL, NULL, NULL),
(2, 'Construction materials', NULL, 1, NULL),
(3, 'Electronics and Optics', NULL, 1, NULL),
(4, 'Food and Beverage', NULL, 1, NULL),
(5, 'Bakery & confectionery products', NULL, NULL, 4),
(6, 'Beverages', NULL, NULL, 4),
(7, 'Fish & fish products', NULL, NULL, 4),
(8, 'Meat & meat products', NULL, NULL, 4),
(9, 'Milk & dairy products', NULL, NULL, 4),
(10, 'Other', NULL, NULL, 4),
(11, 'Sweets & snack food', NULL, NULL, 4),
(12, 'Furniture', NULL, 1, NULL),
(13, 'Bathroom/sauna', NULL, NULL, 12),
(14, 'Bedroom', NULL, NULL, 12),
(15, 'Childrens room', NULL, NULL, 12),
(16, 'Kitchen', NULL, NULL, 12),
(17, 'Living room', NULL, NULL, 12),
(18, 'Office', NULL, NULL, 12),
(19, 'Other (Furniture)', NULL, NULL, 12),
(20, 'Outdoor', NULL, NULL, 12),
(21, 'Project furniture', NULL, NULL, 12),
(22, 'Machinery', NULL, 1, NULL),
(23, 'Machinery components', NULL, NULL, 22),
(24, 'Machinery equipment/tools', NULL, NULL, 22),
(25, 'Manufacture of machinery', NULL, NULL, 22),
(26, 'Maritime', NULL, NULL, 22),
(27, 'Aluminium and steel workboats', 26, NULL, NULL),
(28, 'Boat/Yacht building', 26, NULL, NULL),
(29, 'Ship repair and conversion', 26, NULL, NULL),
(30, 'Metal structures', NULL, NULL, 22),
(31, 'Other', NULL, NULL, 22),
(32, 'Repair and maintenance service', NULL, NULL, 22),
(33, 'Metalworking', NULL, 1, NULL),
(34, 'Construction of metal structures', NULL, NULL, 33),
(35, 'Houses and buildings', NULL, NULL, 33),
(36, 'Metal products', NULL, NULL, 33),
(37, 'Metal works', NULL, NULL, 33),
(38, 'CNC-machining', 37, NULL, NULL),
(39, 'Forgings, Fasteners', 37, NULL, NULL),
(40, 'Gas, Plasma, Laser cutting', 37, NULL, NULL),
(41, 'MIG, TIG, Aluminium welding', 37, NULL, NULL),
(42, 'Plastic and Rubber', NULL, 1, NULL),
(43, 'Packaging', NULL, NULL, 42),
(44, 'Plastic goods', NULL, NULL, 42),
(45, 'Plastic processing technology', NULL, NULL, 42),
(46, 'Blowing', 45, NULL, NULL),
(47, 'Moulding', 45, NULL, NULL),
(48, 'Plastics welding and processing', 45, NULL, NULL),
(49, 'Plastic profiles', NULL, NULL, 42),
(50, 'Printing', NULL, 1, NULL),
(51, 'Advertising', NULL, NULL, 50),
(52, 'Book/Periodicals printing', NULL, NULL, 50),
(53, 'Labelling and packaging printing', NULL, NULL, 50),
(54, 'Textile and Clothing', NULL, 1, NULL),
(55, 'Clothing', NULL, NULL, 54),
(56, 'Textile', NULL, NULL, 54),
(57, 'Wood', NULL, 1, NULL),
(58, 'Other (Wood)', NULL, NULL, 57),
(59, 'Wooden building materials', NULL, NULL, 57),
(60, 'Wooden houses', NULL, NULL, 57),
(61, 'Other', NULL, NULL, NULL),
(62, 'Creative industries', NULL, 61, NULL),
(63, 'Energy technology', NULL, 61, NULL),
(64, 'Environment', NULL, 61, NULL),
(65, 'Service', NULL, NULL, NULL),
(66, 'Business services', NULL, 65, NULL),
(67, 'Engineering', NULL, 65, NULL),
(68, 'Information Technology and Telecommunications', NULL, 65, NULL),
(69, 'Data processing, Web portals, E-marketing', NULL, NULL, 68),
(70, 'Programming, Consultancy', NULL, NULL, 68),
(71, 'Software, Hardware', NULL, NULL, 68),
(72, 'Telecommunications', NULL, NULL, 68),
(73, 'Tourism', NULL, 65, NULL),
(74, 'Translation services', NULL, 65, NULL),
(75, 'Transport and Logistics', NULL, 65, NULL),
(76, 'Air', NULL, NULL, 75),
(77, 'Rail', NULL, NULL, 75),
(78, 'Road', NULL, NULL, 75),
(79, 'Water', NULL, NULL, 75);            
ALTER TABLE "PUBLIC"."SECTOR_TYPE" ADD CONSTRAINT "PUBLIC"."FKOCUPRXDDKA796KNNYQ088IQLI" FOREIGN KEY("CHILD_ID") REFERENCES "PUBLIC"."SECTOR_TYPE"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."PERSON_IN_SECTOR" ADD CONSTRAINT "PUBLIC"."FKQPRP271SIKW2FONXR6LCQD4X0" FOREIGN KEY("PERSON_ID") REFERENCES "PUBLIC"."PERSON"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."SECTOR_TYPE" ADD CONSTRAINT "PUBLIC"."FK2FO216BLIE2VTF7VGB7WN8FTG" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."SECTOR_TYPE"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."SECTOR_TYPE" ADD CONSTRAINT "PUBLIC"."FKJ6LGXRL9V8KD1RQ1CGBX40XFW" FOREIGN KEY("GRANNY_ID") REFERENCES "PUBLIC"."SECTOR_TYPE"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PERSON_IN_SECTOR" ADD CONSTRAINT "PUBLIC"."FKHLRWW6XKK0XXKBOXT6YP3CTUU" FOREIGN KEY("SECTORTYPE_ID") REFERENCES "PUBLIC"."SECTOR_TYPE"("ID") NOCHECK;    
